version: '3.9'
services:
  mysql:
    image: mysql:8.2
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx --sort_buffer_size=512K
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: swarm-api
    mem_limit: 1G
    ports:
      - 5100:3306
    volumes:
      - mysql82:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
#    networks:
#      - gratheon

volumes:
  mysql82:

#networks:
#  gratheon: