version: '3.9'
services:
  mysql:
    image: mysql:8.4
    command: mysqld --mysql-native-password=ON --skip-mysqlx --sort_buffer_size=512K
    environment:
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: swarm-api
    mem_limit: 1G
    ports:
      - 5100:3306
    volumes:
      - mysql84:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - gratheon

volumes:
  mysql84:

networks:
  gratheon: