version: '3.9'
services:
  db-swarm-api-local:
    image: mysql:8
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: swarm-api
    mem_limit: 1G
    ports:
      - 60003:3306
    volumes:
      - db-swarm-api-local:/var/lib/mysql
    network_mode: bridge
    networks:
      - gratheon

volumes:
  db-swarm-api-local:

networks:
  gratheon: